# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class MatriculaAsignaturas(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, asignatura: str=None, nota: str=None, notanumerica: float=None):
        """
        MatriculaAsignaturas - a model defined in Swagger

        :param asignatura: The asignatura of this MatriculaAsignaturas.
        :type asignatura: str
        :param nota: The nota of this MatriculaAsignaturas.
        :type nota: str
        :param notanumerica: The notanumerica of this MatriculaAsignaturas.
        :type notanumerica: float
        """
        self.swagger_types = {
            'asignatura': str,
            'nota': str,
            'notanumerica': float
        }

        self.attribute_map = {
            'asignatura': 'asignatura',
            'nota': 'nota',
            'notanumerica': 'notanumerica'
        }

        self._asignatura = asignatura
        self._nota = nota
        self._notanumerica = notanumerica

    @classmethod
    def from_dict(cls, dikt) -> 'MatriculaAsignaturas':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatriculaAsignaturas of this MatriculaAsignaturas.
        :rtype: MatriculaAsignaturas
        """
        return deserialize_model(dikt, cls)

    @property
    def asignatura(self) -> str:
        """
        Gets the asignatura of this MatriculaAsignaturas.
        asignatura que se va a puntuar

        :return: The asignatura of this MatriculaAsignaturas.
        :rtype: str
        """
        return self._asignatura

    @asignatura.setter
    def asignatura(self, asignatura: str):
        """
        Sets the asignatura of this MatriculaAsignaturas.
        asignatura que se va a puntuar

        :param asignatura: The asignatura of this MatriculaAsignaturas.
        :type asignatura: str
        """

        self._asignatura = asignatura

    @property
    def nota(self) -> str:
        """
        Gets the nota of this MatriculaAsignaturas.
        nota escrita

        :return: The nota of this MatriculaAsignaturas.
        :rtype: str
        """
        return self._nota

    @nota.setter
    def nota(self, nota: str):
        """
        Sets the nota of this MatriculaAsignaturas.
        nota escrita

        :param nota: The nota of this MatriculaAsignaturas.
        :type nota: str
        """

        self._nota = nota

    @property
    def notanumerica(self) -> float:
        """
        Gets the notanumerica of this MatriculaAsignaturas.

        :return: The notanumerica of this MatriculaAsignaturas.
        :rtype: float
        """
        return self._notanumerica

    @notanumerica.setter
    def notanumerica(self, notanumerica: float):
        """
        Sets the notanumerica of this MatriculaAsignaturas.

        :param notanumerica: The notanumerica of this MatriculaAsignaturas.
        :type notanumerica: float
        """

        self._notanumerica = notanumerica

